version: "3"

services:
  api:
    image: jsilva723/api-ixp:v2
    ports:
      - 3001:3001

  client:
    image: nginx:1.21.6-alpine
    depends_on:
      - api
    volumes: 
      - ./client:/usr/share/nginx/html:ro
    ports:
      - 3000:80